branches:
  only:
    - master

language: c
compiler:
  - gcc
  - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check

script: autoreconf -f -i && ./configure --enable-tests && make && make check

notifications:
  irc:
    channels:
      - "chat.freenode.net#iolib"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
