os:
  - freebsd
  - linux
  - osx
dist: jammy
osx_image: xcode14

language: c
compiler:
  - gcc
  - clang

jobs:
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#iolib"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq check; fi

env:
  global:
    # Coverity Scan token
    - secure: "jJirBkZOyJ8KuYXMbjUpKem2FGaCsLBq7roP9oHs5mz8wIKENGB3i7pBe5USVLCwVAuqJ+TPjbfSo4nSnCIf5mLdJoNnyrq8FAYhSRzA/zl4COW6eN0Of9dgCOzcOriPY9rXUVbIapWoMogntnAS6MpmbiSxQCsq99VsIHq3TYk="

before_script:
  - source config/travis.cflags.sh

script:
  - |
      autoreconf -f -i
      tests=disable; if [ "$TRAVIS_OS_NAME" = "linux" ]; then tests=enable; fi
      env CFLAGS="${WERR_CFLAGS}" ./configure --${tests}-tests
      make -j2
      make check

addons:
  coverity_scan:
    project:
      name: sionescu/libfixposix
    build_command_prepend: autoreconf -f -i && ./configure --enable-tests
    build_command: make -j4
    branch_pattern: coverity_scan
    notification_email: sionescu@cddr.org
