name: Build & test

on:
  push:
    branches: [ "master", "ghactions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build deps
        run: sudo apt-get install check
      - name: Checkout
        uses: actions/checkout@v4
      - name: Autoconf
        run: autoreconf -f -i
      - name: Configure
        run: ./configure --enable-tests
      - name: Build
        run: make
      - name: Run tests
        run: make check
      - name: Distcheck
        run: make distcheck
